ALTER TABLE T_CLIENT DROP COLUMN client_id;
ALTER TABLE T_CLIENT ADD COLUMN client_key VARCHAR(255) NOT NULL;

ALTER TABLE T_EVENT DROP COLUMN user_id;
ALTER TABLE T_EVENT ADD COLUMN client_id UUID NOT NULL
    CONSTRAINT t_event_client_id_fk REFERENCES T_CLIENT (id)
    ON UPDATE CASCADE ON DELETE CASCADE;